### ISSUE TITLE
What is anime data table in envirionment variables

### ISSUE THREAD

**Issue by jeydinpham** [KunwarVSuryavanshi/animanga-v2#17]

**Comment by notKvS** [comment]
So once user login, then I am fetching users watchlist from db, and that anime data table is the name of table used. Currently to hide the details about db (table name, column name etc), I am using env variable...later on it will be replaced by separate API.

**Comment by jeydinpham** [comment]
Oh thanks, was just confused because there is some variables used in the code that aren't put in the .env example

**Comment by notKvS** [comment]
Yeah sorry about that, there are few more variables. Maybe later in the evening I'll update it.
