### ISSUE TITLE
CONTINUE WATCHING

### ISSUE THREAD

**Issue by Y345ez** [KunwarVSuryavanshi/animanga-v2#28]
how to make the database work? 
![image](https://github.com/KunwarVSuryavanshi/animanga-v2/assets/94993680/3f815dcd-3b0f-4b83-b268-e2c140150df3)

**Comment by Y345ez** [comment]
I've been trying to add epDetails, aniListId no luck

**Comment by notKvS** [comment]
> I've been trying to add epDetails, aniListId no luck

you can create below columns in supabase, and it should work.
![image](https://github.com/KunwarVSuryavanshi/animanga-v2/assets/35609032/d70f443c-0f2d-4054-a62d-4de1048430fd)

**Comment by Y345Developr** [comment]
It didn't work

**Comment by Y345ez** [comment]
![image](https://github.com/KunwarVSuryavanshi/animanga-v2/assets/94993680/567f250a-1c9a-4360-be87-05ad73feaee0)
> > I've been trying to add epDetails, aniListId no luck
> 
> you can create below columns in supabase, and it should work. ![image](https://user-images.githubusercontent.com/35609032/244300936-d70f443c-0f2d-4054-a62d-4de1048430fd.png)

It didn't work

**Comment by notKvS** [comment]
> ![image](https://user-images.githubusercontent.com/94993680/244348995-567f250a-1c9a-4360-be87-05ad73feaee0.png)
> 
> > > I've been trying to add epDetails, aniListId no luck
> > 
> > 
> > you can create below columns in supabase, and it should work. ![image](https://user-images.githubusercontent.com/35609032/244300936-d70f443c-0f2d-4054-a62d-4de1048430fd.png)
> 
> It didn't work

Is there any error in console?

**Comment by Y345ez** [comment]
> Is there any error in console?

![image](https://github.com/KunwarVSuryavanshi/animanga-v2/assets/94993680/b64af2d7-0ced-4c36-aad4-5305484c597e)
![image](https://github.com/KunwarVSuryavanshi/animanga-v2/assets/94993680/ed6f0ef6-aefd-4526-b02a-140731a3804d)

**Comment by notKvS** [comment]
console error are fine...When are you getting that api key error? For the api key have you pasted those variable in .env file? Are you able to login with supabase?

**Comment by Y345ez** [comment]
> console error are fine...When are you getting that api key error? For the api key have you pasted those variable in .env file? Are you able to login with supabase?

i can sign up but cant login, the api key error are form when i watch a episode and go to anime page , 
and do the api key  is the supabase key?
![image](https://github.com/KunwarVSuryavanshi/animanga-v2/assets/94993680/a8640b20-5bdb-4442-bd92-dd2e76b3b0bd)

**Comment by notKvS** [comment]
Yes the VITE_SUPABASE_KEY is supabase key. It should be visible in your request header like this
![image](https://github.com/KunwarVSuryavanshi/animanga-v2/assets/35609032/3df60d32-85f9-487a-af55-b6816d6b9be3)

**Comment by Y345ez** [comment]
> Yes the VITE_SUPABASE_KEY is supabase key. It should be visible in your request header like this ![image](https://user-images.githubusercontent.com/35609032/244486361-3df60d32-85f9-487a-af55-b6816d6b9be3.png)
ok I have it what can I do now

**Comment by Y345ez** [comment]
Why does it work for you not me

**Comment by notKvS** [comment]
Can u share your deployed instance ..I can take a look at it

**Comment by Y345ez** [comment]
> Owner



> Can u share your deployed instance ..I can take a look at it
ok, I added you to deployed

**Comment by notKvS** [comment]
not the repo...was asking for deployed URL. 
Maybe ping me on discord- KvS#8176

**Comment by notKvS** [comment]
Closing this issue, resolved by correcting implementation of Supabase RLS.
