### ISSUE TITLE
manga need fix 

### ISSUE THREAD

**Issue by Y345ez** [KunwarVSuryavanshi/animanga-v2#32]
![image](https://github.com/KunwarVSuryavanshi/animanga-v2/assets/94993680/982cca08-b55e-4209-b712-1bc3e9a469d8)
![image](https://github.com/KunwarVSuryavanshi/animanga-v2/assets/94993680/e37b7506-d4d5-438b-ab22-1959d364cf7d)

**Comment by notKvS** [comment]
Image proxy is working now although for those chapters where it is showing 0 pages, that can be resolved only once I implement option to change the provider.
